### ISSUE TITLE
running checklist of things to do to setup an automated pi setup with cloud init

### ISSUE THREAD

**Issue by lspitler** [wtgee/huntsman-pocs#218]
Supporting #209 , these are things that the team can help @wtgee with to setup this scheme:

- [ ] zshrc file 
- [ ] use shared `startup.sh` on the ssh mount to customise the startup of each pi (e.g. pull latest docker compose) https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot
- [ ] setup ssh keys
- [ ] auto mount control computer ssh share
- [ ] setup cron jobs (not sure what they are)
- [ ] other post-install commands
- [ ] point to new docker container?
- [ ] filling in all placeholders in current init file
- [ ] extras, e.g. set up cron jobs (downloading IERS for astroplan), auto-start camera services (?), etc.

**Comment by lspitler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [setup and test cloud init](https://trello.com/c/wZKp2f9B/510-setup-and-test-cloud-init)

**Comment by danjampro** [comment]
Superseded by `huntsman-pocs` wiki
