### ISSUE TITLE
main flat field tasks

### ISSUE THREAD

**Issue by lspitler** [wtgee/huntsman-pocs#235]
- [ ] don't save saturated files
- [ ] focus during the day so the flats are focused according to current temperature 
- [ ] validate results during @fergusL MRes thesis are not an issue? see #63 
- [ ] set twilight flat field according to where the sun #64 
- [ ] look out for burn-in #108 
- [ ] implement daytime flat state that happens before sunset - see https://github.com/AstroHuntsman/huntsman-pocs/pull/331/files#r561588170
