### ISSUE TITLE
general observing safety tasks

### ISSUE THREAD

**Issue by lspitler** [wtgee/huntsman-pocs#238]
- [ ] emails on big problems #94 
- [ ] park when internet link or power goes down #74 
- [ ] subsystem health check #138
